# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RaHPlateKeyboard' do
  pod'RaHPlateKeyboard', :path => '/Users/linkaiqi/RaHPlateKeyboard/RaHPlateKeyboard/PlateKeyboard'

end
